server:
  port: 9833

openapi:
  info:
    title: PlayEverland Website API
    short-description: API endpoints for the playeverland.reckful-archive.org website
    source-code-link: https://github.com/ReckfulArchive/playeverland

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    default-models-expand-depth: 2
  disable-i18n: true
